name: Weather App CI & Code Review

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Optional Node setup if you use npm or bundlers like webpack, Vite, etc.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      # Install dependencies if you have package.json, else skip
      - name: Install dependencies
        run: npm install
        if: -f package.json
      
      # Run your build script if exists, else skip
      - name: Build project
        run: npm run build
        if: -f package.json

  code-review:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run CodeRabbit Review
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

